name: build
on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install pebble tool
        run: ./scripts/install-pebble-tool.sh

      - name: Test build all projects
        run: ./scripts/build-all.sh
