name: build
on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build Pebble SDK image
        run: ./scripts/build-pebble-sdk-image.sh

      - name: Ownership
        run: whoami && id

      - name: Test build all projects
        run: ./scripts/build-all.sh "docker run --rm -e HOME=/home/pebble/ -v .:/pebble/ --user $(id -u):$(id -g) pebble-sdk pebble build"
